options_to_attrs:
  - "smagorinsky_enabled"
  - "damping_enabled"
  - "socrates_couple_enabled"
  - "casim_enabled"
  - "galilean_transformation"
  - "time_basis"
  - "use_anelastic_equations"
  - "coriolis_enabled"
  - "diffusion_enabled"
  - "use_viscosity_and_diffusion"
  - "dxx"
  - "dyy"
  - "z_size"
  - "zztop"
  - "dtm"
  - "cfl_cvismax"
  - "cfl_cvelmax"
  - "cfl_dtmmin"
  - "cfl_dtmmax"
  - "surface_pressure"
  - "surface_reference_pressure"
  - "zdmp"
  - "hdmp"
  - "thref0"
  - "l_matchthref"
  - "smag-subc"
  - "smag-subb"
  - "rmlmax"
  - "advection_flow_fields"
  - "advection_theta_field"
  - "advection_q_fields"
  - "l_warm"
  - "number_q_fields"
  - "option"
  - "max_height_cloud"
  - "fixed_cloud_number"
  - "aerosol_option"
  - "rad_start_year"
  - "rad_start_day"
  - "rad_start_time"
  - "l_use_ndrop"
  - "l_fix_re"
  - "mcc_temperature_profile"
  - "mcc_vapour_profile"
  - "mcc_ozone_profile"
  - "dephy_forcings_enabled"
  - "dephy_file"
