global_attributes:
  institution: University of Leeds
  source: MONC
  references: None
  comment: None
global_to_variable:
  - MONC timestamp
options_database:
  variable: options_database
  dimensions:
  - number_options
  - kvp
  required:
  - dxx
  - dyy
  reference_datetime:
  - rad_start_year
  - rad_start_day
  - rad_start_time  # Assume this is in seconds
  options_to_attrs:
  - "smagorinsky_enabled"
  - "damping_enabled"
  - "socrates_couple_enabled"
  - "casim_enabled"
  - "galilean_transformation"
  - "time_basis"
  - "use_anelastic_equations"
  - "coriolis_enabled"
  - "diffusion_enabled"
  - "use_viscosity_and_diffusion"
  - "dxx"
  - "dyy"
  - "z_size"
  - "zztop"
  - "dtm"
  - "cfl_cvismax"
  - "cfl_cvelmax"
  - "cfl_dtmmin"
  - "cfl_dtmmax"
  - "surface_pressure"
  - "surface_reference_pressure"
  - "zdmp"
  - "hdmp"
  - "thref0"
  - "l_matchthref"
  - "smag-subc"
  - "smag-subb"
  - "rmlmax"
  - "advection_flow_fields"
  - "advection_theta_field"
  - "advection_q_fields"
  - "l_warm"
  - "number_q_fields"
  - "option"
  - "max_height_cloud"
  - "fixed_cloud_number"
  - "aerosol_option"
  - "rad_start_year"
  - "rad_start_day"
  - "rad_start_time"
  - "l_use_ndrop"
  - "l_fix_re"
  - "mcc_temperature_profile"
  - "mcc_vapour_profile"
  - "mcc_ozone_profile"
  - "dephy_forcings_enabled"
  - "dephy_file"
time_units: 
  use_input_file: True
  input_file_variable: time
  base_unit: seconds  # Ignored if use_input_file is True
  ref_datetime: options_database  # or ISO format date-time string; ignored if use_input_file is True
  calendar: gregorian # or standard. See https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.CALENDARS. Ignored if use_input_file is True and valid value found there.
add_dimensions:
  x:
    spacing: dxx  # or a numeric value
    position: mid  # end
    attributes:
      axis: X
      units: m
  y: 
    spacing: dyy  # or a numeric value
    position: mid  # end
    attributes:
      axis: Y
      units: m
  xu:
    spacing: dxx  # or a numeric value
    position: end
    attributes:
      axis: X
      units: m
  yv: 
    spacing: dyy  # or a numeric value
    position: end
    attributes:
      axis: Y
      units: m